// src/Components/Layout/footer.jsx
import React from "react";
import {Link} from "react-router-dom";
import logo from "../../Assets/images/logo-white.png";
import x from "../../Assets/images/x.png";
import ln from "../../Assets/images/in.png";
import ig from "../../Assets/images/ig.png";
import call from "../../Assets/images/call.png";
import {BsArrowRightCircle} from "react-icons/bs";

const Footer = () => {
    const social = [
        {img: x, title: "Twitter/X", link: ""},
        {img: ig, title: "Instagram", link: ""},
        {img: ln, title: "LinkedIn", link: ""},
    ];
    return (
        <footer className='bg-black text-gray-200 p-5 py-10 md:py-20'>
            <div className='mx-auto container grid grid-cols-1 md:grid-cols-3 gap-12'>
                <div>
                    <Link to={"/"}>
                        <img src={logo} className='w-40' alt=''/>
                    </Link>
                    <Link
                        className='border-2 text-white flex items-center rounded-md p-3 gap-2 text-sm px-8 mt-10 w-fit cursor-pointer select-none justify-center'
                        to='/contact'
                    >
                        <img src={call} alt='call'/>
                        Schedule a Call
                    </Link>
                </div>
                <div>
                    <h2 className='text-base text-gray-400'>Social</h2>
                    {social.map(({img, title, link}, ind) => (
                        <a
                            className='flex items-center gap-2 my-4'
                            href={link}
                            target='__blank'
                            key={ind}
                        >
                            <img src={img} alt={title}/>
                            <h2>{title}</h2>
                        </a>
                    ))}
                </div>
                <div>
                    <h2 className='text-base text-gray-400 mb-4'>Mailing List</h2>
                    <p className='text-sm'>Stay up to date on our offering.</p>
                    <div className='my-4 relative'>
                        <input
                            type='email'
                            name=''
                            id=''
                            placeholder='enter your email'
                            className='bg-transparent border-b-[1px] w-full p-2'
                        />
                        <BsArrowRightCircle className='absolute bottom-2 right-2 text-xl'/>
                    </div>
                    <p className='text-sm'>
                        By subscribing you agree to with our Privacy Policy and provide
                        consent to receive updates from our company.
                    </p>
                </div>
            </div>
            <div
                className='mx-auto container flex  gap-4 flex-col sm:flex-row items-center justify-between mt-20 text-gray-400 text-sm'>
                <h2>© SecureOps Solutions LLC</h2>
                <div className='flex gap-8'>
                    <Link>Privacy Policy</Link>|<Link>Terms and Services</Link>
                </div>
            </div>
        </footer>
    );
};

export default Footer;

// components/Footer.vue
<script setup lang="ts">
import {useStore} from "~/store";

const store = useStore()

const { ltd } = storeToRefs(store)

const onClickLtd = () =>  ltd.value = !ltd.value
const footerNavigation = {
  connect: [
    {name: 'Instagram', href: '#'},
    {name: 'Twitter/X', href: '#'},
    {name: 'LinkedIn', href: '#'},
  ],
  company: [
    {name: 'About', href: '/about'},
    {name: 'Services', href: 'services'},
    // {name: 'Blog', href: '#'},
    {name: 'Contact us', href: '/contact-us'},
  ],
}
</script>

<template>
  <footer class="relative font-display mx-auto mt-32 container px-6 lg:px-8">
    <div class="border-t border-gray-900/10 py-16 sm:py-24 lg:py-32">
      <div class="xl:flex xl:justify-between xl:gap-8">
        <nuxt-link to="/ltd" v-if="ltd">
          <img class="h-9" src="/logo-ltd.png"
               alt="SecureOps Solutions LTD"/>
        </nuxt-link>
        <nuxt-link to="/" v-else>
          <img class="h-9" src="/logo.png"
               alt="SecureOps Solutions LLC"/>
        </nuxt-link>
        <div class="mt-16 grid grid-cols-2 gap-8 xl:w-[30%] xl:mt-0">
          <div>
            <h3 class="text-sm/6 font-semibold text-gray-900">Solutions</h3>
            <ul role="list" class="mt-6 space-y-4">
              <li v-for="item in footerNavigation.company" :key="item.name">
                <a :href="item.href" class="text-sm/6 text-gray-600 hover:text-gray-900">{{ item.name }}</a>
              </li>
            </ul>
          </div>
          <div class="mt-10 md:mt-0">
            <h3 class="text-sm/6 font-semibold text-gray-900">Support</h3>
            <ul role="list" class="mt-6 space-y-4">
              <li v-for="item in footerNavigation.connect" :key="item.name">
                <a :href="item.href" class="text-sm/6 text-gray-600 hover:text-gray-900">{{ item.name }}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<style scoped></style>
